config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/create'

  get 'users/update'

  get 'users/edit'

  get 'users/destroy'

  get 'users/delete'

  get 'users/index'

  get 'users/show'

  get 'readings/new'

  get 'readings/create'

  get 'readings/update'

  get 'readings/edit'

  get 'readings/destroy'

  get 'readings/delete'

  get 'readings/index'

  get 'readings/show'

  get 'about/index'

  get 'about' => 'about#index'

  root 'users#show'

  resources :users
  resources :readings

end

app/models/reading.rb
class Reading < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About Us';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  def new
    @page_title = 'Add New Reading'
    @reading = Reading.new
    @user = User.new
  end

  def create
    @reading = Reading.new(reading_params)
    @reading.save

    redirect_to readings_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def delete
  end

  def index
  end

  def show    
  end

  private
    def reading_params
    params.require(:reading).permit(:read_at, :user_id, :value)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @page_title = 'Add New User'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save

    redirect_to users_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def delete
  end

  def index
  end

  def show
    @readings = Reading.where(user_id: 1)
  end

  private
    def user_params
    params.require(:user).permit(:first_name, :last_name, :address)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1><%=@page_title%></h1>
<p>This is about the view</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : 'Welcome' %> | Utility Manager </title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= javascript_include_tag "http://www.google.com/jsapi" %>  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--js and style for chartkick -->
  <%= javascript_include_tag "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'users' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
            <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>            
          </ul>
          <ul class="nav navbar-nav navbar-right">            
            <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><%= link_to 'User', new_user_path %></li>
	            <li><%= link_to 'Reading', new_reading_path %></li>
	          </ul>
	        </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

<header>
	<div class="container">
		<h1>Utility Manger <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
	</div>
</header>

<section>
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<%= yield %>
			</div>
		
			<div class="col-md-4">
				<%= render 'partials/sidebar' %>
			</div>
		</div>
	</div>
</section>

<footer>
	<div class="container">
		<p>Copyright &copy; 2015, All Rights Reserved </p>
	</div>
</footer>

</body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
	<div class="well">
		<h3>Location Info </h3>
		<ul>
			<li> Utility Manager </li>
			<li> 50 Nanyang Avenue </li>
			<li> Singapore, 639738 </li>
			<li> Email: support@utilitymanager.com</li>
		</ul>
	</div>
<% end %>

app/views/readings/create.html.erb
<h1>Readings#create</h1>
<p>Find me in app/views/readings/create.html.erb</p>

app/views/readings/delete.html.erb
<h1>Readings#delete</h1>
<p>Find me in app/views/readings/delete.html.erb</p>

app/views/readings/destroy.html.erb
<h1>Readings#destroy</h1>
<p>Find me in app/views/readings/destroy.html.erb</p>

app/views/readings/edit.html.erb
<h1>Readings#edit</h1>
<p>Find me in app/views/readings/edit.html.erb</p>

app/views/readings/index.html.erb
<h1>Readings#index</h1>
<p>Find me in app/views/readings/index.html.erb</p>

app/views/readings/new.html.erb
<h2>Add New Reading</h2>

<%= form_for @reading do |f| %>
	
	<div class="form-group">
		<%= f.label :user %><br />
		<%= f.select :user_id, User.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]} %>
	</div>
	<div class="form-group">
		<%= f.label :read_at %><br />
		<%= f.datetime_select :read_at %><br />
	</div>
	<div class="form-group">
		<%= f.label :value %><br />
		<%= f.text_field :value, class:'form-control' %><br />
	</div>
	
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", readings_path, class:'btn btn-default' %>

<% end %>

app/views/readings/show.html.erb
<h2>Chart</h2>

<div class="row">

  <!-- Line Chart - Single Series -->
  <div class="col-xs-6">
    <h3>Visits By Day</h3>
    <%= line_chart @readings.group_by_day(:read_at, format: "%B %d, %Y").count, discrete: true %>
  </div>

</div>

app/views/readings/update.html.erb
<h1>Readings#update</h1>
<p>Find me in app/views/readings/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h2>Add New User</h2>

<%= form_for @user do |f| %>

	<div class="form-group">
		<%= f.label :first_name %><br />
		<%= f.text_field :first_name, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :last_name %><br />
		<%= f.text_field :last_name, class:'form-control' %><br />
	</div>
	<div class="form-group">
		<%= f.label :address %><br />
		<%= f.text_field :address, class:'form-control' %><br />
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", users_path, class:'btn btn-default' %>

<% end %>

app/views/users/show.html.erb
<h2>Chart</h2>

<div class="row">

  <!-- Line Chart - Single Series -->
  <div class="col-xs-6">
    <h3>Readings By Day</h3>
    <%= line_chart @readings.group_by_day(:read_at, format: "%B %d, %Y").sum(:value), discrete: true %>
  </div>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>